# Generated by Django 6.0.4 on 2026-05-08 07:18

import photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='images', validators=[photos.validators.validate_file_size]),
        ),
    ]
